services:
  neo4j:
    image: neo4j:4.4
    container_name: bloodhound-neo4j
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_default__listen__address=0.0.0.0  # Allow listening on all interfaces
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0  # Enable remote Bolt access
      - NEO4J_dbms_connector_http_listen__address=0.0.0.0  # Enable remote HTTP access
    ports:
      - "7474:7474"  # HTTP port for the web interface
      - "7687:7687"  # Bolt port for BloodHound connections
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/import
      - neo4j_plugins:/plugins
    restart: always  # Automatically restart the container

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
